import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import {ClerkProvider} from "@clerk/nextjs"
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "LinkedIn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <Navbar />
        <div className="flex-1 w-full bg-[#F4F2EE]">
          <main className="max-w-[80%]   mx-auto ">{children}
            
          </main>
          <Footer />
        </div>
      </body>
    </html>
    </ClerkProvider>
  );
}
